# Generated by Django 4.1.7 on 2023-04-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='dummy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
