# Generated by Django 4.1.7 on 2023-04-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_score_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='dummy',
        ),
    ]
